@section('senate')
    <div class="item-page">
        <h2>Senaat Winters (2012)</h2>
    <div class="content_pages">
        <p><span class="gen"><strong>Senaat Winters</strong><br><br> De Senaat is het bestuur en het officiële visitekaartje van de GSV. Woensdag 13 september 2012 is Senaat Winters in de volgende samenstelling aangetreden:<br><br> </span>Praeses: Lennard Winters<br> Assessor primus: Mark van Dijk<br> Fiscus: Lodewijk Boersema <br>Abactis: Laura Brands<br> Assessor secundus: Tiny Hoving<span class="gen"><br> </span></p>
    <p><img class="blackborder" src="../forum/images/senaatwinters/senaat%20winters.jpg" border="0" alt="Senaat Boersema" width="567" height="336" style="border: 0px none; display: block; margin-left: auto; margin-right: auto;"><br><br><span class="gensmall"><br> </span><strong>Lennard Winters, Praeses</strong></p>
    <p>Lennard is a<img class="blackborder" src="../forum/images/senaatwinters/lennard.jpg" border="0" width="130" align="left" style="float: left; border: 0;">an de ene kant een constante factor, maar aan de andere kant ook wel een niet-constante factor binnen de Senaat (ja, maar toch ook nee). Hij doet altijd alsof zijn enige bezigheden in de week ON-4 en chillen aan de Eendrachtskade zijn, terwijl hij eigenlijk altijd wel druk bezig is met belangrijke dingen. Lennard is een gezelligheidsdier: altijd op zoek naar iemand om een biertje mee te drinken of te ouwehoeren aan een bar ergens. Als verschrikkelijk actief GSV’er maakt Lennard tevens een beetje het beeld goed dat bestaat van het H-clubje. Als iemand Lennard blij wil maken met een kadootje kan die persoon het beste een stressbal of iets dergelijks kopen. Lennard heeft namelijk altijd wel iets in zijn handen waar hij aan zit te frunniken. Als het geen pen is, is het wel een speldje, manchetknoop, of iets anders dat niet van hemzelf is. In conclusie is Lennard de, maar ook een baas.<br><br><strong>Laura Brands, Abactis</strong><br><br><img class="blackborder" src="../forum/images/senaatwinters/laura.jpg" border="0" width="130" align="right" style="float: right; border: 0;"></p>
    <p class="MsoNormal">In en in senator der GSV. Natuurlijk schrijft Laura wel eens een briefje naar een zusje in den lande, maar haar hart ligt bij de GSV en dat is te merken! Ze is net dat ene getal waardoor je Excel bestand net klopt. Die net significante dataset in je SPSS, precies het goede artikel bij je meta-analyse. Laura is die betrouwbare schakel binnen de Senaat waar je op terug kunt vallen, die bijvoorbeeld de verwarming aanzet in een ijzige senaatskamer een uurtje voor de vergadering begint. Wat Laura precies allemaal doet is niet echt te beschrijven, behalve door te stellen dat als ze er niet zou zijn de Senaat met meer dan een vijfde van zijn kracht zou afnemen. Absoluut van toegevoegde waarde voor het team: zij maakt het verschil.</p>
    <p class="MsoNormal"><br><br><strong>Lodewijk Boersema, Fiscus</strong><br><br><img class="blackborder" src="../forum/images/senaatwinters/lodewijk.jpg" border="0" width="130" align="left" style="float: left; border: 0;"> Amice Boersema is vet belangrijk voor onze Senaat. Met zijn ongekende enthousiasme voor cijferwerk gecombineerd met droge gevoel voor humor is hij van toegevoegde waarde voor ons allen. Zoals hij nummertjes keurig geordend op cd’tjes brandt, zo staan uw schulden aan hem op zijn netvlies gebrand. Met zijn helder blauwe oogjes houdt hij zicht op al uw inkomsten en uitgaven en slaat toe wanneer de tijd rijp is. Dat zijn gehoor hem nog wel eens in de steek laat levert meer hilarische dan vervelende momenten op. Lodewijk, je bent vet belangrijk.</p>
    <p><br><br><br><strong>Mark van Dijk, Assessor I</strong><br><br><img class="blackborder" src="../forum/images/senaatwinters/mark.jpg" border="0" width="130" align="right" style="float: right; border: 0;"></p>
    <p class="MsoNormal">Mark is de senator met de wildste cowboyideeën van het gezelschap. Hij stroomt vaak over van enthousiasme, (en dat werkt aanstekelijk!) niet in de minste plaats om de GSV op de kaart te zetten in de stad. Dat is mooi, want dat is dan ook een van zijn taken als assessor primus. Mark doet daarbij zijn zaken met stijl. Hij voelt zich als een vis in het water in een pak en doet altijd zijn best om zijn das precies goed te strikken. Hoewel er geen twijfel over kan bestaan dat hij ook ervan houdt om in zijn trainingsbroek te chillen. Nog een kwaliteit van hem die vast te pas komt als primus is dat Mark eerlijk voor zijn mening durft uit te komen. Als je met Mark praat, kun je discussiëren over van alles en nog wat en ontdekken dat hij geïnteresseerd is en goed geïnformeerd en staat voor wat hij zegt. Met Mark in de Senaat is het nooit saai en zal hij zijn medesenatoren nog vaak onderhouden over studentikoze grappen van jaren geleden, of mooie besluiten uit 1976.</p>
    <p><br><br><br><strong>Tiny Hoving, Assessor II</strong><br><br><img class="blackborder" src="../forum/images/senaatwinters/tiny.jpg" border="0" width="130" align="left" style="float: left; border: 0;"></p>
    <p class="MsoNormal" style="margin-bottom: .0001pt;">Tiny, vol enthousiasme deelt zij haar ideeën met de groep. Ideeën,<span style="mso-spacerun: yes;">&nbsp; </span>die vaak ter plekke nog geformuleerd worden.Hierbij wordt te pas en te onpas al ratelend nieuwe woorden en gezegden aan ons vocabulaire toegevoegd.</p>
    <p class="MsoNormal" style="margin-bottom: .0001pt;">Tiny is de geheugensteun van de Senaat. Zij zorgt ervoor dat alle essentiële informatie het papier bereikt en bewaard wordt voor de komende generaties. <span style="mso-spacerun: yes;">&nbsp;</span>Zij zorgt dat onze buiken altijd gevuld zijn door consequent te laat te komen op de vergaderingen en dit meer dan goed te maken in de keuken.</p>
    <p class="MsoNormal" style="margin-bottom: .0001pt;">Zij zorgt ervoor dat de vereniging blijft draaien en is in de niet sarcastische zin van het woord écht belangrijk!</p>
    <p>&nbsp;</p>
        </div>
    </div>
@stop